# Netlify 빌드 및 함수 설정
[build]
  # 빌드 명령은 따로 필요하지 않으며, Netlify가 Go 함수를 자동으로 감지하고 빌드합니다.
  # publish 디렉토리는 정적 사이트가 있을 경우 설정합니다. 없으면 생략 가능합니다.
  publish = "public" 

[functions]
  # Go 함수가 위치한 디렉토리를 지정합니다.
  # 이 디렉토리 내의 각 하위 디렉토리는 개별 함수가 됩니다.
  directory = "netlify/functions"

# 아래 설정은 필수는 아니지만, Go 버전을 명시하고 싶을 때 유용합니다.
# [build.environment]
#   GO_VERSION = "1.21" 
